app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # portfolioのurls.pyを読み込み
    path('', include('portfolio.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/portfolio/urls.py
from django.urls import path
from . import views

app_name= 'portfolio'
urlpatterns = [
    # viewsからindexを読み込んで、nameをindexに
    path('', views.index, name='index'),
    path('works', views.works, name='works'),
]

app/portfolio/models.py
from django.db import models

# Create your models here.


class Profile(models.Model):

    name = models.CharField('名前', max_length=100)
    image = models.ImageField('イメージ', upload_to='profile')
    career = models.CharField('職業', max_length=55, null=True, blank=True)
    org = models.CharField('所属組織', max_length=55, null=True, blank=True)
    age = models.CharField('年齢', max_length=55, null=True, blank=True)
    twitter = models.URLField('TwitterのURL', null=True, blank=True)
    facebook = models.URLField('FacebookのURL', null=True, blank=True)
    instagram = models.URLField('InstagramのURL', null=True, blank=True)
    introduction = models.TextField('自己紹介文')

    class Meta:
        verbose_name_plural = 'プロフィール'


class Description(models.Model):

    text = models.CharField('本文', max_length=255)

    def __str__(self):
        return self.text

    class Meta:
        verbose_name_plural = 'スキルの概要文'


class Skill(models.Model):

    name = models.CharField('名前', max_length=100)
    years = models.FloatField('経験年数', default=0)
    description = models.ForeignKey(Description, on_delete=models.SET_NULL, null=True, verbose_name='説明文')

    def years_rounded(self):
        years = self.years
        if years.is_integer():
            years = int(years)
        return years

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'スキル'


class Work(models.Model):

    title = models.CharField('タイトル', max_length=100)
    image = models.ImageField('イメージ', upload_to='works', null=True, blank=True)
    url = models.URLField('URL')
    published = models.DateField('公開日', null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = '作品'

app/portfolio/views.py
from django.shortcuts import render

from .models import Profile, Skill, Work


def index(request):
    profile = Profile.objects.all().last()
    skills = Skill.objects.all()
    works = Work.objects.all().order_by('-published')[:3]

    context = {
        'profile': profile,
        'skills': skills,
        'works': works,
    }
    return render(request, 'index.html', context)

def works(request):
    works = Work.objects.all().order_by('-published')
    context = {
        'works': works,
    }
    return render(request, 'works.html', context)

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfolio</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@300;400;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/portfolio.css' %}">
</head>
<body>
    
    {% block main %}{% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block main %}

<header class="header">
  <div class="container">
    <div class="text-center">
      <div class="mb-4">
        <img src="{{ profile.image.url }}" height="180" width="180" class="rounded-circle img-center-cover" alt="">
      </div>
      <div>
        <h2 class="text-dark header-title mb-3">{{ profile.name }}</h2>
        <div class="mb-3">
          {% if profile.career %}
          <span>{{ profile.career }}</span>
          <span>/</span>
          {% endif %}
          {% if profile.org %}
          <span>{{ profile.org }}</span>
          {% if profile.age %}
          <span>/</span>
          {% endif %}
          {% endif %}
          {% if profile.age %}
          <span>{{ profile.age }}歳</span>
          {% endif %}
        </div>
        <div class="mb-4">
          {% if profile.twitter %}<a href="{{ profile.twitter }}" target="_blank"><i class="fab fa-twitter sns-icon text-twitter"></i></a>{% endif %}
          {% if profile.facebook %}<a href="{{ profile.facebook }}" target="_blank"><i class="fab fa-facebook sns-icon text-facebook"></i></a>{% endif %}
          {% if profile.instagram %}<a href="{{ profile.instagram }}" target="_blank"><i class="fab fa-instagram sns-icon text-instagram"></i></a>{% endif %}
        </div>
        <div class="row">
          <div class="col-md-9 mx-auto">
            <div class="jumbotron bg-light py-4">
              <div class="container text-left">
                <p class="lead text-dark">{{ profile.introduction|safe|linebreaksbr }}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

<section class="mb-100">
  <div class="container">
    <div>
      <h3 class="display-4 font-weight-bold text-primary">SKILLS</h3>
      <div class="row">
        <div class="col-md-10 mx-auto py-4">
          <table class="table table-borderless">
            {% for skill in skills %}
            <tr>
              <td class="align-middle h4 font-weight-bold text-dark">{{ skill.name }}</td>
              <td class="align-middle"><span class="badge badge-primary py-1 px-2 font-14">{{ skill.years_rounded }}年</span></td>
              <td class="align-middle">{{ skill.description.text }}</td>
            </tr>
            {% endfor %}
          </table>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="mb-5">
  <div class="container">
    <div>
      <h3 class="display-4 font-weight-bold text-primary">WORKS</h3>
      <div class="row">
        {% for work in works %}
        <div class="col-lg-4 mb-3">
          <a href="{{ work.url }}" target="_blank">
            <div class="card shadow-sm border border-light">
              <div>
                <img src="{% if work.image %}{{ work.image.url }}{% else %}{% static 'assets/img/sample.jpg' %}{% endif %}" class="w-100 img-center-cover" height="200" alt="">
              </div>
              <div class="p-3">
                <h5 class="text-dark mb-0">{{ work.title }}</h5>
              </div>
            </div>
          </a>
        </div>
        {% endfor %}
      </div>
      <div class="text-right">
        <a href="{% url 'portfolio:works' %}" class="btn btn-lg btn-primary">View All Works <i class="far fa-list-alt pl-1"></i></a>
      </div>
    </div>
  </div>
</section>

{% endblock %}

app/templates/works.html
{% extends 'base.html' %}
{% load static %}

{% block main %}

<section>
  <a href="/" class="left-top"><i class="fas fa-arrow-left"></i> 戻る</a>
  <div class="container">
    <div class="text-center py-5">
      <h3 class="display-4 font-weight-bold text-primary">WORKS</h3>
    </div>
    <div class="row">
    {% for work in works %}
      <div class="col-lg-4 mb-3">
        <a href="{{ work.url }}" target="_blank">
          <div class="card shadow-sm border border-light">
            <div>
              <img src="{% if work.image %}{{ work.image.url }}{% else %}{% static 'assets/img/sample.jpg' %}{% endif %}" class="w-100 img-center-cover" height="200" alt="">
            </div>
            <div class="p-3">
              <h5 class="text-dark mb-0">{{ work.title }}</h5>
            </div>
          </div>
        </a>
      </div>
    {% endfor %}
    </div>
  </div>
</section>

{% endblock %}